[[config]]
name = "Odoo Dev"
# Dynamic paths - odoo-env can generate a .odools-active.toml file
# that extends this config with the paths of the active version
odoo_path = "${workspaceFolder}/src/community/master"
addons_paths = [
    "${workspaceFolder}/src/community/master/addons",
    "${workspaceFolder}/src/community/master/odoo/addons",
    "${workspaceFolder}/src/enterprise/master",
]
python_path = "${workspaceFolder}/.venv/bin/python3"
