"""IDE workspace generation and path building."""
from __future__ import annotations

import json
import os
from pathlib import Path

import oo as _pkg
from oo.config import Config
from oo.git import branch_to_dir


def discover_addons_paths(repo_path: Path) -> list[Path]:
    """Scan repo for Odoo module directories; return their parent dirs as addons paths."""
    SKIP = {"node_modules", ".git", "__pycache__", "setup"}
    addons_dirs: set[Path] = set()
    for manifest in repo_path.rglob("__manifest__.py"):
        if any(p in SKIP for p in manifest.parts):
            continue
        addons_dirs.add(manifest.parent.parent)
    return sorted(addons_dirs) if addons_dirs else [repo_path]


def build_paths(community_path: Path, extra_worktrees: dict[str, Path]) -> tuple[str, str]:
    python_path = str(community_path)
    addons_parts = [
        str(community_path / "addons"),
        str(community_path / "odoo" / "addons"),
    ]
    for repo_path in extra_worktrees.values():
        for p in reversed(discover_addons_paths(repo_path)):
            addons_parts.insert(0, str(p))
    return python_path, ",".join(addons_parts)


def profile_worktree_paths(config: Config, profile_name: str) -> dict[str, Path] | None:
    """Return {repo: worktree_path} for a profile, checking only existing paths on disk.

    Returns None if the community worktree is missing (profile not set up yet).
    """
    profile = next((p for p in config.profiles if p.name == profile_name), None)
    if not profile:
        return None

    community_spec = profile.branch_specs.get("community")
    if not community_spec:
        return None

    community_path = _pkg.SRC_DIR / "community" / branch_to_dir(community_spec.branch)
    if not community_path.is_dir():
        return None

    paths: dict[str, Path] = {"community": community_path}
    for repo, spec in profile.branch_specs.items():
        if repo == "community":
            continue
        p = _pkg.SRC_DIR / repo / branch_to_dir(spec.branch)
        if p.is_dir():
            paths[repo] = p

    return paths


def generate_odools_config(
    env_name: str,
    worktree_paths: dict[str, Path],
    python_path: str,
    config: Config | None = None,
) -> Path:
    """Write odools.toml for the Odoo LSP (gitignored, regenerated each run).

    When config is provided, also generates [[config]] sections for all other
    profiles whose community worktree exists on disk.
    """
    from oo.ui import log_ok

    def _config_lines_for(name: str, paths: dict[str, Path], py_path: str) -> list[str]:
        comm = paths["community"]
        ent = paths.get("enterprise")
        ap: list[str] = []
        if ent:
            ap.append(str(ent))
        ap.append(str(comm / "addons"))
        ap.append(str(comm / "odoo" / "addons"))
        for repo, path in paths.items():
            if repo not in ("community", "enterprise"):
                for p in discover_addons_paths(path):
                    ap.append(str(p))
        section = [
            "[[config]]",
            f'name = "Odoo Dev — {name}"',
            f'odoo_path = "{comm}"',
            "addons_paths = [",
        ]
        for p in ap:
            section.append(f'    "{p}",')
        section.append("]")
        section.append(f'python_path = "{py_path}"')
        return section

    lines = ["# Auto-generated by oo — do not edit manually",
             f"# Active environment: {env_name}", ""]
    lines.extend(_config_lines_for(env_name, worktree_paths, python_path))

    if config is not None:
        for profile in config.profiles:
            if profile.name == env_name:
                continue
            other_paths = profile_worktree_paths(config, profile.name)
            if other_paths is None:
                continue
            lines.append("")
            lines.extend(_config_lines_for(profile.name, other_paths, python_path))

    lines.append("")
    out = _pkg.ROOT_DIR / "odools.toml"
    out.write_text("\n".join(lines))
    log_ok(f"Generated: {out.relative_to(_pkg.ROOT_DIR)}")
    return out


def generate_vscode_workspace(
    name: str,
    worktree_paths: dict[str, Path],
    env: dict[str, str],
    odoo_rc_path: str,
) -> Path:
    """Generate a VS Code .code-workspace file for the environment."""
    from oo.ui import log_ok
    env_dir = _pkg.ROOT_DIR / ".cache" / "envs" / name
    out = env_dir / f"{name}.code-workspace"

    folders = []
    for repo, path in worktree_paths.items():
        rel = os.path.relpath(path, env_dir)
        folders.append({"name": repo, "path": rel})
    folders.append({"name": "odoo-env", "path": os.path.relpath(_pkg.ROOT_DIR, env_dir)})

    venv_python = str(_pkg.ROOT_DIR / ".venv" / "bin" / "python3")
    terminal_env = {k: v for k, v in env.items() if v}
    launch_env = {k: v for k, v in env.items() if v and k != "PATH"}
    launch_env["PYTHONPATH"] = "${workspaceFolder:community}"
    launch_env["ODOO_PATH"] = "${workspaceFolder:community}"
    launch_env["COMMUNITY"] = "${workspaceFolder:community}"

    def _launch_config(label: str, args: list) -> dict:
        return {
            "name": label,
            "type": "debugpy",
            "request": "launch",
            "console": "integratedTerminal",
            "cwd": "${workspaceFolder:community}",
            "program": "odoo-bin",
            "justMyCode": False,
            "pythonArgs": ["-Xfrozen_modules=off"],
            "args": args,
            "env": launch_env,
        }

    workspace = {
        "folders": folders,
        "settings": {
            "python.defaultInterpreterPath": venv_python,
            "search.useIgnoreFiles": False,
            "[python]": {
                "editor.defaultFormatter": "charliermarsh.ruff"
            },
            "files.exclude": {
                "**/__pycache__": True,
                "**/*.pyc": True,
                "**/node_modules": True,
            },
            "search.exclude": {
                "**/__pycache__": True,
                "**/*.pyc": True,
                "**/node_modules": True,
            },
            "Odoo.selectedProfile": f"Odoo Dev — {name}",
            "terminal.integrated.env.linux": terminal_env,
            "terminal.integrated.env.osx": terminal_env,
        },
        "launch": {
            "version": "0.2.0",
            "configurations": [
                _launch_config("Start Odoo", [
                    f"--config={odoo_rc_path}",
                    "--dev=all",
                ]),
                _launch_config("Start Debug Shell", [
                    "shell",
                    f"--config={odoo_rc_path}",
                    "--dev=all",
                ]),
                _launch_config("Run Console Tests", [
                    f"--config={odoo_rc_path}",
                    "--dev=all",
                    "--test-enable",
                    "--test-tags=${input:odooTestTags}",
                    "--stop-after-init",
                ]),
            ],
            "inputs": [
                {
                    "id": "odooTestTags",
                    "type": "promptString",
                    "description": "Choose a type of tests. Prefixes are: <none> for tags, / for modules, : for classes, . for methods.",
                }
            ],
        },
    }

    env_dir.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(workspace, indent=2))
    log_ok(f"Generated: {out.relative_to(_pkg.ROOT_DIR)}")
    return out


def generate_zed_workspace(
    name: str,
    worktree_paths: dict[str, Path],
    env: dict[str, str],
) -> None:
    """Generate Zed workspace: symlinks to worktrees + .zed/settings.json."""
    from oo.ui import log_ok
    env_dir = _pkg.ROOT_DIR / ".cache" / "envs" / name
    env_dir.mkdir(parents=True, exist_ok=True)

    for repo, path in worktree_paths.items():
        link = env_dir / repo
        if link.exists() or link.is_symlink():
            link.unlink()
        rel = os.path.relpath(path, env_dir)
        link.symlink_to(rel)

    venv_python = str(_pkg.ROOT_DIR / ".venv" / "bin" / "python3")
    settings = {
        "tab_size": 4,
        "lsp": {
            "basedpyright": {
                "settings": {
                    "python.pythonPath": venv_python,
                }
            }
        },
        "terminal": {
            "env": {
                "ODOO_ENV_NAME": env.get("ODOO_ENV_NAME", name),
                "ODOO_RC": env.get("ODOO_RC", ""),
                "PYTHONPATH": env.get("PYTHONPATH", ""),
                "ODOO_PATH": env.get("ODOO_PATH", ""),
                "COMMUNITY": env.get("COMMUNITY", ""),
            }
        },
        "file_scan_exclusions": [
            "**/__pycache__",
            "**/node_modules",
            "**/*.pyc",
        ],
    }

    zed_dir = env_dir / ".zed"
    zed_dir.mkdir(parents=True, exist_ok=True)
    zed_settings = zed_dir / "settings.json"
    zed_settings.write_text(json.dumps(settings, indent=2))
    log_ok(f"Generated: {zed_settings.relative_to(_pkg.ROOT_DIR)}")


def generate_idea_project(
    name: str,
    worktree_paths: dict[str, Path],
    env: dict[str, str],
) -> None:
    """Generate a minimal JetBrains/PyCharm project in .cache/envs/{name}/.idea/."""
    from oo.ui import log_ok
    env_dir = _pkg.ROOT_DIR / ".cache" / "envs" / name
    idea_dir = env_dir / ".idea"
    idea_dir.mkdir(parents=True, exist_ok=True)

    iml_name = f"odoo-{name}.iml"
    (idea_dir / ".name").write_text(f"odoo-{name}")

    (idea_dir / "modules.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<project version="4">\n'
        '  <component name="ProjectModuleManager">\n'
        '    <modules>\n'
        f'      <module fileurl="file://$PROJECT_DIR$/.idea/{iml_name}" filepath="$PROJECT_DIR$/.idea/{iml_name}" />\n'
        '    </modules>\n'
        '  </component>\n'
        '</project>\n'
    )

    (idea_dir / "misc.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<project version="4">\n'
        '  <component name="ProjectRootManager" version="2"'
        ' project-jdk-name="Python 3.12 (odoo-env)" project-jdk-type="Python SDK" />\n'
        '</project>\n'
    )

    content_root_lines: list[str] = []
    for repo, path in worktree_paths.items():
        content_root_lines.append(f'    <content url="file://{path}">')
        content_root_lines.append(f'      <excludeFolder url="file://{path}/node_modules" />')
        content_root_lines.append(f'      <excludeFolder url="file://{path}/__pycache__" />')
        content_root_lines.append('    </content>')

    content_roots_str = "\n".join(content_root_lines)
    (idea_dir / iml_name).write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<module type="PYTHON_MODULE" version="4">\n'
        '  <component name="NewModuleRootManager" inherit-compiler-output="true">\n'
        '    <exclude-output />\n'
        f'{content_roots_str}\n'
        '    <orderEntry type="inheritedJdk" />\n'
        '    <orderEntry type="sourceFolder" forTests="false" />\n'
        '  </component>\n'
        '</module>\n'
    )

    log_ok(f"Generated: {idea_dir.relative_to(_pkg.ROOT_DIR)}")
