"""IDE workspace generation and path building."""
from __future__ import annotations

import json
import os
from pathlib import Path

import oo as _pkg
from oo.config import Config
from oo.git import branch_to_dir


def discover_addons_paths(repo_path: Path) -> list[Path]:
    """Scan repo for Odoo module directories; return their parent dirs as addons paths."""
    SKIP = {"node_modules", ".git", "__pycache__", "setup"}
    addons_dirs: set[Path] = set()
    for manifest in repo_path.rglob("__manifest__.py"):
        if any(p in SKIP for p in manifest.parts):
            continue
        addons_dirs.add(manifest.parent.parent)
    return sorted(addons_dirs) if addons_dirs else [repo_path]


def build_paths(community_path: Path, extra_worktrees: dict[str, Path]) -> tuple[str, str]:
    python_path = str(community_path)
    addons_parts = [
        str(community_path / "addons"),
        str(community_path / "odoo" / "addons"),
    ]
    for repo_path in extra_worktrees.values():
        for p in reversed(discover_addons_paths(repo_path)):
            addons_parts.insert(0, str(p))
    return python_path, ",".join(addons_parts)


def profile_worktree_paths(config: Config, profile_name: str) -> dict[str, Path] | None:
    """Return {repo: worktree_path} for a profile, checking only existing paths on disk.

    Returns None if the community worktree is missing (profile not set up yet).
    """
    profile = next((p for p in config.profiles if p.name == profile_name), None)
    if not profile:
        return None

    community_spec = profile.branch_specs.get("community")
    if not community_spec:
        return None

    community_path = _pkg.SRC_DIR / "community" / branch_to_dir(community_spec.branch)
    if not community_path.is_dir():
        return None

    paths: dict[str, Path] = {"community": community_path}
    for repo, spec in profile.branch_specs.items():
        if repo == "community":
            continue
        p = _pkg.SRC_DIR / repo / branch_to_dir(spec.branch)
        if p.is_dir():
            paths[repo] = p

    return paths


def generate_odools_config(
    env_name: str,
    worktree_paths: dict[str, Path],
    python_path: str,
    config: Config | None = None,
) -> Path:
    """Write odools.toml for the Odoo LSP (gitignored, regenerated each run).

    When config is provided, also generates [[config]] sections for all other
    profiles whose community worktree exists on disk.
    """
    from oo.ui import log_ok

    def _config_lines_for(name: str, paths: dict[str, Path], py_path: str) -> list[str]:
        comm = paths["community"]
        ent = paths.get("enterprise")
        ap: list[str] = []
        if ent:
            ap.append(str(ent))
        ap.append(str(comm / "addons"))
        ap.append(str(comm / "odoo" / "addons"))
        for repo, path in paths.items():
            if repo not in ("community", "enterprise"):
                for p in discover_addons_paths(path):
                    ap.append(str(p))
        section = [
            "[[config]]",
            f'name = "Odoo Dev — {name}"',
            f'odoo_path = "{comm}"',
            "addons_paths = [",
        ]
        for p in ap:
            section.append(f'    "{p}",')
        section.append("]")
        section.append(f'python_path = "{py_path}"')
        return section

    lines = ["# Auto-generated by oo — do not edit manually",
             f"# Active environment: {env_name}", ""]
    lines.extend(_config_lines_for(env_name, worktree_paths, python_path))

    if config is not None:
        for profile in config.profiles:
            if profile.name == env_name:
                continue
            other_paths = profile_worktree_paths(config, profile.name)
            if other_paths is None:
                continue
            lines.append("")
            lines.extend(_config_lines_for(profile.name, other_paths, python_path))

    lines.append("")
    out = _pkg.ROOT_DIR / "odools.toml"
    out.write_text("\n".join(lines))
    log_ok(f"Generated: {out.relative_to(_pkg.ROOT_DIR)}")
    return out


def generate_vscode_workspace(
    name: str,
    worktree_paths: dict[str, Path],
    env: dict[str, str],
    odoo_rc_path: str,
) -> Path:
    """Generate a VS Code .code-workspace file for the environment."""
    from oo.ui import log_ok
    env_dir = _pkg.ROOT_DIR / "workspaces" / name
    out = env_dir / f"{name}.code-workspace"

    folders = []
    for repo, path in worktree_paths.items():
        rel = os.path.relpath(path, env_dir)
        folders.append({"name": repo, "path": rel})
    folders.append({"name": "odoo-env", "path": os.path.relpath(_pkg.ROOT_DIR, env_dir)})

    venv_python = str(_pkg.ROOT_DIR / ".venv" / "bin" / "python3")
    terminal_env = {k: v for k, v in env.items() if v}
    launch_env = {k: v for k, v in env.items() if v and k != "PATH"}
    launch_env["PYTHONPATH"] = "${workspaceFolder:community}"
    launch_env["ODOO_PATH"] = "${workspaceFolder:community}"
    launch_env["COMMUNITY"] = "${workspaceFolder:community}"

    def _launch_config(label: str, args: list) -> dict:
        return {
            "name": label,
            "type": "debugpy",
            "request": "launch",
            "console": "integratedTerminal",
            "cwd": "${workspaceFolder:community}",
            "program": "odoo-bin",
            "justMyCode": False,
            "pythonArgs": ["-Xfrozen_modules=off"],
            "args": args,
            "env": launch_env,
        }

    workspace = {
        "folders": folders,
        "settings": {
            "python.defaultInterpreterPath": venv_python,
            "search.useIgnoreFiles": False,
            "[python]": {
                "editor.defaultFormatter": "charliermarsh.ruff"
            },
            "files.exclude": {
                "**/__pycache__": True,
                "**/*.pyc": True,
                "**/node_modules": True,
            },
            "search.exclude": {
                "**/__pycache__": True,
                "**/*.pyc": True,
                "**/node_modules": True,
            },
            "Odoo.selectedProfile": f"Odoo Dev — {name}",
            "terminal.integrated.env.linux": terminal_env,
            "terminal.integrated.env.osx": terminal_env,
        },
        "launch": {
            "version": "0.2.0",
            "configurations": [
                _launch_config("Start Odoo", [
                    f"--config={odoo_rc_path}",
                    "--dev=all",
                ]),
                _launch_config("Start Debug Shell", [
                    "shell",
                    f"--config={odoo_rc_path}",
                    "--dev=all",
                ]),
                _launch_config("Run Console Tests", [
                    f"--config={odoo_rc_path}",
                    "--dev=all",
                    "--test-enable",
                    "--test-tags=${input:odooTestTags}",
                    "--stop-after-init",
                ]),
            ],
            "inputs": [
                {
                    "id": "odooTestTags",
                    "type": "promptString",
                    "description": "Choose a type of tests. Prefixes are: <none> for tags, / for modules, : for classes, . for methods.",
                }
            ],
        },
    }

    env_dir.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(workspace, indent=2))
    log_ok(f"Generated: {out.relative_to(_pkg.ROOT_DIR)}")
    return out


def generate_zed_workspace(
    name: str,
    worktree_paths: dict[str, Path],
    env: dict[str, str],
) -> None:
    """Generate Zed workspace: symlinks, .zed/settings.json, tasks.json, launch.json."""
    from oo.ui import log_ok
    env_dir = _pkg.ROOT_DIR / "workspaces" / name / "zed"
    env_dir.mkdir(parents=True, exist_ok=True)

    # Symlinks for each worktree
    for repo, path in worktree_paths.items():
        link = env_dir / repo
        if link.exists() or link.is_symlink():
            link.unlink()
        rel = os.path.relpath(path, env_dir)
        link.symlink_to(rel)

    # Symlink: odoo-env → ROOT_DIR (access to oo scripts, configs, etc.)
    odoo_env_link = env_dir / "odoo-env"
    if odoo_env_link.exists() or odoo_env_link.is_symlink():
        odoo_env_link.unlink()
    odoo_env_link.symlink_to(os.path.relpath(_pkg.ROOT_DIR, env_dir))

    # Symlink: odools.toml → ROOT_DIR/odools.toml
    odools_link = env_dir / "odools.toml"
    if odools_link.exists() or odools_link.is_symlink():
        odools_link.unlink()
    odools_link.symlink_to(os.path.relpath(_pkg.ROOT_DIR / "odools.toml", env_dir))

    venv_dir = str(_pkg.ROOT_DIR / ".venv")
    venv_python = str(_pkg.ROOT_DIR / ".venv" / "bin" / "python3")
    venv_bin = str(_pkg.ROOT_DIR / ".venv" / "bin")

    terminal_env = {k: v for k, v in env.items() if v}
    terminal_env["VIRTUAL_ENV"] = venv_dir
    terminal_env["PATH"] = venv_bin + ":" + terminal_env.get("PATH", "")

    settings = {
        "tab_size": 4,
        "lsp": {
            "basedpyright": {
                "settings": {
                    "python.pythonPath": venv_python,
                    "python.venvPath": str(_pkg.ROOT_DIR),
                    "python.venv": ".venv",
                }
            },
            "odoo-ls": {
                "binary": {
                    "path": str(_pkg.ROOT_DIR / ".venv" / "bin" / "odoo-ls"),
                    "arguments": [],
                },
                "settings": {
                    "Odoo.selectedProfile": f"Odoo Dev \u2014 {name}",
                },
            },
        },
        "terminal": {"env": terminal_env},
        "file_scan_exclusions": [
            "**/__pycache__",
            "**/node_modules",
            "**/*.pyc",
        ],
    }

    odoo_rc = env.get("ODOO_RC", "")
    community = env.get("COMMUNITY", "")
    odoo_bin = community + "/odoo-bin"

    tasks = [
        {
            "label": "Start Odoo",
            "command": "python",
            "args": [odoo_bin, f"--config={odoo_rc}", "--dev=all"],
            "cwd": community,
            "use_new_terminal": False,
            "allow_concurrent_runs": False,
            "reveal": "always",
        },
        {
            "label": "Start Debug Shell",
            "command": "python",
            "args": [odoo_bin, "shell", f"--config={odoo_rc}", "--dev=all"],
            "cwd": community,
            "use_new_terminal": False,
            "allow_concurrent_runs": False,
            "reveal": "always",
        },
        {
            "label": "Run Console Tests",
            "command": "python",
            "args": [
                odoo_bin,
                f"--config={odoo_rc}",
                "--dev=all",
                "--test-enable",
                "--test-tags=",
                "--stop-after-init",
            ],
            "cwd": community,
            "use_new_terminal": False,
            "allow_concurrent_runs": False,
            "reveal": "always",
        },
    ]

    launch_env = {k: v for k, v in env.items() if v and k != "PATH"}
    launch = {
        "version": "0.2.0",
        "configurations": [
            {
                "name": "Debug Odoo",
                "type": "debugpy",
                "request": "launch",
                "console": "integratedTerminal",
                "cwd": community,
                "program": odoo_bin,
                "justMyCode": False,
                "pythonArgs": ["-Xfrozen_modules=off"],
                "args": [f"--config={odoo_rc}", "--dev=all"],
                "env": launch_env,
            },
            {
                "name": "Debug Shell",
                "type": "debugpy",
                "request": "launch",
                "console": "integratedTerminal",
                "cwd": community,
                "program": odoo_bin,
                "justMyCode": False,
                "pythonArgs": ["-Xfrozen_modules=off"],
                "args": ["shell", f"--config={odoo_rc}", "--dev=all"],
                "env": launch_env,
            },
            {
                "name": "Run Console Tests",
                "type": "debugpy",
                "request": "launch",
                "console": "integratedTerminal",
                "cwd": community,
                "program": odoo_bin,
                "justMyCode": False,
                "pythonArgs": ["-Xfrozen_modules=off"],
                "args": [
                    f"--config={odoo_rc}",
                    "--dev=all",
                    "--test-enable",
                    "--test-tags=",
                    "--stop-after-init",
                ],
                "env": launch_env,
            },
        ],
    }

    zed_dir = env_dir / ".zed"
    zed_dir.mkdir(parents=True, exist_ok=True)
    (zed_dir / "settings.json").write_text(json.dumps(settings, indent=2))
    (zed_dir / "tasks.json").write_text(json.dumps(tasks, indent=2))
    (zed_dir / "launch.json").write_text(json.dumps(launch, indent=2))
    log_ok(f"Generated: {(zed_dir / 'settings.json').relative_to(_pkg.ROOT_DIR)}")
